Correct_time()
inbo/camtrapdp pull request #108
Opened 2024-07-17 14:49 UTC by sannegovaert

fix #105

2024-07-23 15:39 UTC, damianooldoni requested changes
Very nice! And I like the tests a lot too. 

I requested changes as tests should also take into account the changes in `x$data$observations` and `x$data$media`.

I have also committed directly to improve some aspects:
- Remove the "hack" by using the `{{ }}` embracing operator from rlang. See related commit for more information about it.
- Capitalize comments.
- Add some informative comments 
- Remove typos
- Use `purrr::pluck()` instead of `deployments(x)$` syntax as we do in other functions.
- Improve function documentation by adding hyperlinks where needed.
- Use `cli::cli_alert_succes())` for output message. It's visually appealing and the message can be captured as a class.
- Suppress messages where testing are not returning errors: this helps to have a cleaner test console output.
- Solve the test about the returned message.
- Run `devtools::document()`: it modified the rendered documentation of other functions as well.

2024-07-23 15:39 UTC, damianooldoni commented on tests/testthat/test-correct_time.R
> +})
We should also test that observations and media are changed.

2024-07-23 15:39 UTC, damianooldoni commented on tests/testthat/test-correct_time.R
> +})
Same here: media and observations are also changed and so tests should be added.

2024-07-24 13:01 UTC, damianooldoni approved these changes
Well done 👍

2024-09-05 09:48 UTC, peterdesmet approved these changes
Nice work @sannegovaert ! I changed some things, mainly in f6142d66d3617bcd7e2c3c72ac4eb6db47c8b39b

- Indicate in documentation what values get changed
- Don't show all valid deploymentIDs in error message (too verbose)
- Don't warn on duplicates (just do it)
- Only set timestampIssues to FALSE for selected deployments (not all)
- Wrap text in alert_success
- Remove test "correct_time() returns no error on valid deploymentID"

For some reason, I'm getting errors when using `cli::cli_alert_success()` over `cli::cli_inform()`, so I reverted to the latter. I'll create an issue if anyone wants to investigate this further.

2024-09-05 09:49 UTC, peterdesmet commented
I have also updated the function name to `shift_time()`, so that users don't get the impression the function can correct the time for them.

2024-09-05 10:03 UTC, merged