Create `contributors()`
inbo/camtrapdp pull request #140
Opened 2024-11-05 12:19 UTC by sannegovaert

fix #136

2025-05-21 14:41 UTC, peterdesmet requested changes
Great, I think we're almost there. Main changes:

- Guarantee columns title, path, email, organization, role are returned by `contributors()`.
- Move a bit more of the parsing logic to `create_eml_contributors()` rather than directly in `write_eml()`

2025-05-21 14:41 UTC, peterdesmet commented on R/write_eml.R
>      dplyr::filter(!.data$role %in% c("rightsHolder", "publisher")) %>%
We'll have to make sure this works if no `role` is assigned. Guaranteeing columns should be done in `contributors()`

2025-05-21 14:41 UTC, peterdesmet commented on R/write_eml.R
>        last_name = purrr::map_chr(
Note that the IPT will already provide a `firstName` and `lastName` in addition to the `title`. I would update `contributors()` to provide those columns (from `title`) _if they are not yet provided_. Name them `firstName` and `lastName` (camelCase, not snake_case).

2025-05-21 14:41 UTC, peterdesmet commented on tests/testthat/test-write_eml.R
> +      title = "Sanne Govaert",
Can you update this to a dummy name, with orcid 0000-0000-0000-0000. That makes it easier to recognize in the snapshot.

2025-05-22 12:29 UTC, sannegovaert commented on R/write_eml.R
>        last_name = purrr::map_chr(
> Note that the IPT will already provide a `firstName` and `lastName` in addition to the `title`. I would update `contributors()` to provide those columns (from `title`) _if they are not yet provided_. Name them `firstName` and `lastName` (camelCase, not snake_case).

You want this to be added to the dataframe that `contributors(x)` returns?
But then it's likely that, if users are updating the contributors, that these new parameters will be added to `x$contributors`.
And following [Data Package](https://specs.frictionlessdata.io/data-package/#metadata) that is not allowed, as I understand correctly?

2025-05-23 17:28 UTC, peterdesmet reviewed
Well done @sannegovaert, this was another big one 😅 Let's merge before the weekend 😄 

Note: `contributors()` is also a function in base R, which we will now mask. I don't immediately see how we can use a better name to avoid that.

2025-05-23 17:29 UTC, merged