Add taxonomy function
inbo/camtrapdp pull request #38
Opened 2024-03-20 10:26 UTC by damianooldoni

This PR adds `taxonomy()` function as described in #17. Tests are also added.

Some work still to be done after #28 is merged.

2024-03-20 11:08 UTC, PietrH commented
#28 was merged

2024-03-21 09:41 UTC, PietrH commented
I'm getting a R CMD Check note: 

```
N  checking R code for possible problems (4.1s)
   read_camtrapdp: no visible binding for global variable ‘scientificName’
   read_camtrapdp: no visible binding for global variable
     ‘taxon.scientificName’
   Undefined global functions or variables:
     scientificName taxon.scientificName
```

This line is the culprit: 

https://github.com/inbo/camtrapdp/blob/fc5126460b07f858239808042fbb4497eccb3b83/R/read_camtrapdp.R#L53

2024-03-21 09:45 UTC, damianooldoni commented
> I'm getting a R CMD Check note:
> 
> ```
> N  checking R code for possible problems (4.1s)
>    read_camtrapdp: no visible binding for global variable ‘scientificName’
>    read_camtrapdp: no visible binding for global variable
>      ‘taxon.scientificName’
>    Undefined global functions or variables:
>      scientificName taxon.scientificName
> ```
> 
> This line is the culprit:
> 
> https://github.com/inbo/camtrapdp/blob/fc5126460b07f858239808042fbb4497eccb3b83/R/read_camtrapdp.R#L53

Solve via [bb20dd4](https://github.com/inbo/camtrapdp/pull/38/commits/bb20dd43fbb5ca482030e523d1e150f4cbc7bcac)

2024-03-21 11:03 UTC, PietrH requested changes

2024-03-21 11:03 UTC, PietrH commented on tests/testthat/test-taxonomy.R
We should check that taxonomy() doesn't result in observations being repeated after the `left_join`

2024-03-21 12:33 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
> +  )
This is actually what I had in my mind, actually. I agree with you that hard coding is the best way for writing codes.
However, @peterdesmet didn't want to hard code the column names, unless I misunderstood him?

2024-03-21 12:34 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
> +  expect_equal(nrow(taxa),10)
Fair enough! Precise as much as possible. Thanks.

2024-03-21 12:37 UTC, damianooldoni commented on tests/testthat/test-observations.R
> +library(purrr)
I'll try to remember it.

2024-03-21 12:53 UTC, damianooldoni commented on tests/testthat/test-build_taxonomy.R
> +test_that("build_taxonomy() returns a tibble data frame", {
Thanks. I set it back to data frame but forgot to modify also the documentation. Good catch!

2024-03-21 13:01 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
> +  )
Discussed internally. Just now. We all agree on hard coding the columns 🚀

2024-03-21 13:04 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
> +  dataset <- example_dataset()
Nice idea! Any reader, even "future-me" will appreciate it for sure.

2024-03-21 13:15 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
Except for the columns/rows order of checks, I follow your scheme. 
Decided to first check cols and then rows.

2024-03-21 13:19 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
Decided just now to not check/return warning for duplicates returned in `taxonomy()`.

2024-03-21 13:31 UTC, damianooldoni commented on tests/testthat/test-taxonomy.R
> +    dataset <- example_dataset()
good idea.

2024-03-21 15:05 UTC, PietrH commented
I'm going to leave this to Peter to review this time.

2024-03-21 20:28 UTC, damianooldoni commented
Thanks @peterdesmet and @PietrH. Now, to merge this, we need an approved review.

2024-03-22 10:52 UTC, peterdesmet approved these changes

2024-03-22 11:46 UTC, merged